services:
  voicebox:
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    networks:
      - voicebox-net

  desktop:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "34115:34115"
    volumes:
      - .:/app
      - /app/frontend/node_modules

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "50021:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - voicebox
    networks:
      - voicebox-net

networks:
  voicebox-net:
    driver: bridge
