version: '3'

tasks:
  init:
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - npm i
    desc: 'Install Wails and run npm install'
  dev:
    cmds:
      - wails dev
    desc: 'Run Wails development server'
